#! /bin/sh
#
# Configuration file for bspwm, a tiling window-manager

# Load the colors from the Solarized color-scheme
. ~/.colorschemes/CURRENT.bash

# Set border colors
bspc config normal_border_color		$color04
bspc config active_border_color 	$color07
bspc config focused_border_color 	$color07
bspc config presel_feedback_color	$color0C

# Set some usage configurations
bspc config split_ratio			    0.50
bspc config initial_polarity		first_child
bspc config history_aware_focus  	true
bspc config focus_by_distance    	true
bspc config focus_follows_pointer   true

# Set monocle layout settings
bspc config borderless_monocle		false
bspc config gapless_monocle		    false
bspc config paddingless_monocle		false
bspc config single_monocle		    false

# Set window configuration
bspc config top_padding			    $PANEL_HEIGHT
bspc config border_width         	1
bspc config window_gap          	12

# Create desktops and set appropriate rules
bspc monitor -d Main Web Mail Other

bspc rule -a Firefox desktop=^2
bspc rule -a Thunderbird desktop=^3
bspc rule -a libprs500 desktop=^4
