#! /bin/sh
#
# Configuration file for bspwm, a tiling window-manager

# Load the colors from the Solarized color-scheme
. ~/.solarized-colors

# Set border colors
bspc config normal_border_color		$S_BASE02
bspc config active_border_color 	$S_BASE01
bspc config focused_border_color 	$S_BASE1
bspc config presel_feedback_color	$S_BLUE

# Set some usage configurations
bspc config split_ratio			    0.50
bspc config initial_polarity		second_child
bspc config history_aware_focus  	true
bspc config focus_by_distance    	true

# Set monocle layout settings
bspc config borderless_monocle		true
bspc config gapless_monocle		    true
bspc config paddingless_monocle		false
bspc config single_monocle		    true

# Set window configuration
bspc config top_padding			    $PANEL_HEIGHT
bspc config border_width         	2
bspc config window_gap          	12

# Create desktops and set appropriate rules
bspc monitor -d Main Firefox Mail Media Other
bspc rule -a Firefox desktop=^2
bspc rule -a Thunderbird desktop=^3
bspc rule -a Wine desktop=^4
