#!/bin/bash
#
# lpassmenu is a script that copies LastPass passwords to the clipboard
# using dmenu to select the proper site

# Set lastpass user
USER=wlong799@gmail.com
HEIGHT=32
FONT="xft:Source Code Pro"

# Read line by line
IFS=$'\n'

# Log in to LastPass if not already logged in
status=`lpass status`
if [[ $status == "Not logged in." ]]; then
    lpass login --trust $USER
fi

# Get all LastPass entries and format them properly
readarray entries < <( lpass ls )
new_entries=()
for entry in "${entries[@]}"; do
    if [[ entry != ^\ +$ ]]; then
        new_entries+=($entry)
    fi
done
entries=("${new_entries[@]}")
unset new_entries

entries=( "${entries[@]#[A-Z]*/}" )
entries=( "${entries[@]%\ \[id:\ [0-9]*\]}" )

# Obtain proper website using dmenu
website=$(printf '%s\n' "${entries[@]}" | dmenu -h $HEIGHT -fn $FONT)

# Back up previous primary/clipboard selections and overwrite with password
PRIMARY=`xsel -op`
CLIPBOARD=`xsel -ob`

lpass show --password "$website" | tr -d "\n" | xsel -i
xsel -op | xsel -ib

# Wait for user to paste in password, and then restore original selections
sleep 5s
echo $PRIMARY | xsel -i
echo $CLIPBOARD | xsel -ib
