#! /bin/sh
#
# Formats output for use by lemonbar

# load solarized colors
. ~/.solarized-colors 

# determine number of monitors
num_mon=$(bspc query -M | wc -l)

# Read in lines of input on desktop state from mkpanel
while read -r line ; do
    case $line in
        D*)
            # time output from date
            datetime="%{F-}%{B-} ${line#?} "
            ;;
        T*)
            # window title output from xtitle
            title="%{F-}%{B-} ${line#?}"
            ;;
        W*)
            # bspwm state output from bspc subscribe report
            wm=""
            # iterate through each section separately
            IFS=':' 
            set -- ${line#?} #
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [mM]*)
                        # monitor information, skipped if multiple monitors not present
                        [ $num_mon -lt 2 ] && shift && continue
                        case $item in
                            m*)
                                # monitor
                                FG=-
                                BG=-
                                ;;
                            M*)
                                # focused monitor
                                FG=-
                                BG=-
                                ;;
                        esac
                        # add clickable monitor icons to bspwm status 
                        wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}"
                        ;;
                    [fFoOuU]*)
                        # desktop information
                        case $item in
                            f*)
                                # free desktop
                                FG=$S_BASE1
                                BG=-
                                ;;
                            F*)
                                # focused free desktop
                                FG=$S_BASE1
                                BG=$S_BASE03
                                ;;
                            o*)
                                # occupied desktop
                                FG=-
                                BG=-
                                ;;
                            O*)
                                # focused occupied desktop
                                FG=-
                                BG=$S_BASE03
                                ;;
                            u*)
                                # urgent desktop
                                FG=$S_ORANGE
                                BG=-
                                ;;
                            U*)
                                # focused urgent desktop
				FG=$S_ORANGE
                                BG=$S_BASE03
                                ;;
                        esac
                        # add clickable desktop icons to bspwm status
                        wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}"
                        ;;
                esac
                # move to next parameter
                shift
            done
            ;;
    esac
    # bspwm status aligned left, title in center, clock on right
    printf "%s\n" "%{l}${wm}%{c}${title}%{r}${datetime}"
done
